### PR TITLE
logging/print_logs=yes_by_default

### PR DESCRIPTION
**Pull request by pinikomarov**
This should make logging enabled by default

### CODE REVIEW

**Comment by manosnoam** [comment]
Thanks for suggestion, I think the default should be "do not collect logs", unless requested with --print-logs.

Anyhow it is better to:
1) Change the trap command from ERR to EXIT, in trap_function_on_error()
or
2) Move collect_submariner_info to the end (but it might be ignored, if the script exited with unexpected termination)

**Comment by pinikomarov** [comment]
I prefer option 1 , but right now it's on EXIT : 
https://github.com/manosnoam/ocp-multi-cluster-tester/blob/6eb5786c13f941674455f0e946125381620fe5de/helper_functions#L119
No?

**Comment by manosnoam** [comment]
Yes.
Now it will collect logs all the time, unless ALL E2E tests have passed
(i.e. everything is good :)

**Comment by manosnoam** [comment]
Pini I'm closing this one. If you're still seeing a problem please let me know, thanks!

**Pull request closed without merging**
